# Generated by Django 5.2.3 on 2025-06-29 19:11

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Images pour le feed principal', upload_to='feed/', verbose_name='Image')),
                ('alt_text', models.CharField(help_text="Description de l'image pour l'accessibilité", max_length=200, verbose_name='Texte alternatif')),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feed',
                'verbose_name_plural': 'Feed',
                'ordering': ['ordre_affichage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(help_text='Recommandé : 600x400px', upload_to='news/', verbose_name='Image')),
                ('lien_externe', models.URLField(verbose_name='Lien externe')),
                ('plateforme', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('blog', 'Blog'), ('youtube', 'YouTube')], max_length=50, verbose_name='Plateforme')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['ordre_affichage', '-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('token_desabonnement', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Token de désabonnement')),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_partenaire', models.CharField(max_length=100, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(help_text='Recommandé : format carré 200x200px, fond transparent', upload_to='partners/', verbose_name='Logo')),
                ('url_site', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre_affichage', 'nom_partenaire'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('pseudo', models.CharField(max_length=50, unique=True, verbose_name='Pseudo')),
                ('titre_professionnel', models.CharField(max_length=200, verbose_name='Titre professionnel')),
                ('bio', models.TextField(verbose_name='Biographie')),
                ('photo_profil', models.ImageField(help_text='Recommandé : 400x400px', upload_to='profile/', verbose_name='Photo de profil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('description_courte', models.TextField(help_text='Résumé en 300 caractères max', max_length=300, verbose_name='Description courte')),
                ('description_detaillee', models.TextField(help_text='Description complète pour la page détail', verbose_name='Description détaillée')),
                ('image', models.ImageField(help_text='Recommandé : 800x600px', upload_to='projects/', verbose_name='Image du projet')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('lance', 'Lancé'), ('beta', 'Beta'), ('termine', 'Terminé'), ('pause', 'En pause')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('technologies', models.JSONField(default=list, help_text='Ex: ["React", "Django", "PostgreSQL"]', verbose_name='Technologies utilisées')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('featured', models.BooleanField(default=False, verbose_name='Projet mis en avant')),
                ('url_demo', models.URLField(blank=True, null=True, verbose_name='URL de démo')),
                ('url_github', models.URLField(blank=True, null=True, verbose_name='URL GitHub')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['ordre_affichage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_competence', models.CharField(max_length=100, verbose_name='Nom de la compétence')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('icone_class', models.CharField(help_text='Ex: fas fa-code, fas fa-brain', max_length=50, verbose_name="Classe d'icône")),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['ordre_affichage', 'nom_competence'],
            },
        ),
        migrations.CreateModel(
            name='SocialGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recommandé : 600x600px', upload_to='gallery/', verbose_name='Image')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description_courte', models.TextField(help_text='Résumé en 300 caractères max', max_length=300, verbose_name='Description courte')),
                ('contenu_detaille', models.TextField(help_text='Contenu complet pour la page détail', verbose_name='Contenu détaillé')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galerie sociale',
                'verbose_name_plural': 'Galerie sociale',
                'ordering': ['ordre_affichage', '-created_at'],
            },
        ),
    ]
